pipeline {
    agent any

    stages {
        stage('Hello'){
            steps{
                echo 'Hello, World!'
                sh 'echo "This is a shell command execution."'
            }
        }
    }
}