pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'golang:trixie'
                    reuseNode true
                }
            }

            environment {
                HOME = "${WORKSPACE}"
                GOCACHE = "${WORKSPACE}/.cache/go-build"
                GOMODCACHE = "${WORKSPACE}/.cache/go-mod"
            }

            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p $GOCACHE $GOMODCACHE
                        export PATH="$PATH:$HOME/go/bin"

                        go env
                        go install github.com/jstemmer/go-junit-report/v2@latest
                        go test -v ./... 2>&1 | go-junit-report > test-results.xml
                    '''
                }
            }

            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }

            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }

            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
