pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent{
                docker {
                    image 'golang:trixie'
                    reuseNode true
                }
            }
            
        environment {
            HOME = "${WORKSPACE}"
            GOCACHE = "${WORKSPACE}/.cache/go-build"
            GOMODCACHE = "${WORKSPACE}/.cache/go-mod"
        } 

        steps {
            dir('bugtracker-backend') {
                sh '''
                    mkdir -p $GOCACHE $GOMODCACHE
                    go env
                    go test -v ./...
                '''
            }
            }
        }
}